### ISSUE TITLE
Can't add plugins

### ISSUE THREAD

**Issue by dmamira** [warashibe/nextdapp-cli#3]
When I tried to add the fb plugin, I got the following error and could not install it.
```
$ nextdapp add fb
{}
fb
warashibe.nextdapp/fb
help us prioritize new features and bug fixes by enabling us to collect anonymous statistics about your usage. sharing anonymous usage information is completely voluntary and helps us improve Bit and build a better product.
for more information see analytics documentation - https://docs.bit.dev/docs/conf-analytics
would you like to help Bit with anonymous usage analytics? [yes(y)/no(n)]:  (yes) 
(node:17230) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```
What's the solution?
Thank you.

**Comment by tn0ms** [comment]
this looks like just a warning and not an error. Could you check if it's actually not installed under `/nd/fb`.
Also please make sure `nextdapp` CLI tools are the latest version. We are in alpha and moving very fast, so your nextdapp might be an old version.

```
yarn global upgrade nextdapp
```

Could you try

```bash
nextdapp create myapp
cd myapp
nextdapp add fb
```

and see if it fails?

**Comment by dmamira** [comment]
I ran them, but still got the same warning and the plugin would not install.
I'm using nextdapp@0.9.0, bit-bin@14.7.6 and node@14.3.0.
Thank you.

**Comment by dmamira** [comment]
I ran the following command before running ```nextdapp add fb``` and it installed successfully.
```
mkidr myapp
cd myapp
bit init
bit import warashibe.nextdapp/fb
```
Thank you.
